version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_bar
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certbot/aaa:/var/aaa/certbot
      - ./nginx/ssl:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/aaa:/var/aaa/certbot
      - ./nginx/ssl:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot
      --webroot-path=/var/www/certbot
      --email your@email.com
      --agree-tos
      --no-eff-email
      -d aaa.com
      && echo '✅ Сертификат получен.'"